
POWERLEVEL9K_PROMPT_ON_NEWLINE=true

POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_SECOND_PROMPT_PREFIX="%K{232}%F{green} $%f%k%F{232}\uE0B0%f "

POWERLEVEL9K_CONTEXT_TEMPLATE="%F{yellow}%n%F{233}@%f%F{red}%m%f"

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(history status background_jobs context dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(vcs time dir_writable)

POWERLEVEL9K_CHANGESET_HASH_LENGTH=7
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_OS_ICON_BACKGROUND="232"
POWERLEVEL9K_OS_ICON_FOREGROUND="112"

POWERLEVEL9K_HISTORY_BACKGROUND='232'
POWERLEVEL9K_HISTORY_FOREGROUND='031'

POWERLEVEL9K_STATUS_OK_BACKGROUND="232"
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"

POWERLEVEL9K_STATUS_ERROR_BACKGROUND="232"
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

POWERLEVEL9K_TIME_BACKGROUND='232'
POWERLEVEL9K_TIME_FOREGROUND='026'

POWERLEVEL9K_DIR_HOME_BACKGROUND='232'
POWERLEVEL9K_DIR_HOME_FOREGROUND='036'

POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='232'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='036'

POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='232'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='036'

POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='232'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='red'

POWERLEVEL9K_VCS_CLEAN_BACKGROUND='232'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='119'

POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='232'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='136'

POWERLEVEL9K_VCS_UNTRACKED_ICON='\uF059'
POWERLEVEL9K_VCS_MODIFIED_ICON='\uF059'
POWERLEVEL9K_VCS_BRANCH_ICON='\uE0A0 '

POWERLEVEL9K_VCS_UNSTAGED_ICON="\uF111"
POWERLEVEL9K_VCS_STAGED_ICON="\uF111"

POWERLEVEL9K_VCS_UNTRACKED_ICON="\uF069"
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON="\u2193"
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON="\u2191"
POWERLEVEL9K_VCS_COMMIT_ICON=''
POWERLEVEL9K_VCS_GIT_ICON='\uF1D3  '
POWERLEVEL9K_LOCK_ICON='\uE0A2'

POWERLEVEL9K_VCS_STASH_ICON='\uF16C' # \uF01C

POWERLEVEL9K_HOME_ICON="\uF17C "
POWERLEVEL9K_HOME_SUB_ICON="\uF17C "
POWERLEVEL9K_FOLDER_ICON="\uF17C "
POWERLEVEL9K_LINUX_ICON="\uF17C"
